### PR TITLE
Recommend  to use  "ProcessBuilder" class to run the process 

### PR DESCRIPTION
**Pull request by lak-proddev**
Signed-off-by: Lakshminarayana Nekkanti <narayana.nekkanti@gmail.com>

Recommend  to use  "ProcessBuilder" class to run the process

### CODE REVIEW

**Comment by jonas-jonas** [comment]
run tests

**Comment by jonas-jonas** [comment]
I think you pushed a wrong commit on this PR? Could you please revert the last commit?

**Comment by lak-proddev** [comment]
Done. Yes, it should be in a different branch

**Comment by jonas-jonas** [comment]
Thanks.

**Comment by jonas-jonas** [comment]
Sorry for the noise.

**Pull request merged**
