### PR TITLE
#155 installation and build problems

### PR DESCRIPTION
**Pull request by wimjongman**
* Updated to latest repo
* Moved WWD inclusion to dependency
* Updated README

### CODE REVIEW

**Comment by jonas-jonas** [comment]
Hi,

thank you for submitting the PR. Do you happen to know, how this will work if the feature is installed from the marketplace? If that works the same way, I'm happy to merge this PR.

**Comment by wimjongman** [comment]
It depends on what you put on marketplace. If you install it including WWD (as it is now) AND another version of WWD is already installed then the install will fail as you can see in issue #155. 

With my patch, the installation will also fail if WWD is not installed. So WWD needs to be installed first. 

To solve this properly you need to put WWD as a separate feature in the update site and put it as an optional feature on the marketplace entry.

Can you put me on the build whitelist so that my pull requests get build by Jenkins?

**Comment by vogella** [comment]
@wimjongman looks like you did you add the signed by: Wim Jongman (wim.jongman@****.com) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

**Comment by wimjongman** [comment]
It seems like an unneccesary requirements since author and committer are already in the commit. We should get rid of that,

**Comment by vogella** [comment]
Something the foundation needs to do I think

Wim Jongman <notifications@github.com> schrieb am Fr., 27. Dez. 2019, 18:17:

**Comment by wimjongman** [comment]
> 
> Something the foundation needs to do I think

Yes. I filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653

**Comment by wimjongman** [comment]
I also added WWD to the update site. On every build it will pull the latest WWD into the repo. Please add wwd as an optional installation feature on the marketplace and all will be fine from that point on.

**Comment by jonas-jonas** [comment]
Hi,
sorry for the delays.

I tested your changes locally and that seems to be a very good solution. I will merge this now and manually check an installation from the marketplace. Thanks for taking the time!

**Comment by wimjongman** [comment]
Jonas, you might have to add the WWD feature as optional to the market place entry.

**Comment by jonas-jonas** [comment]
Awesome. This does work as intended with the marketplace. Thanks again and sorry for the delays!

> Jonas, you might have to add the WWD feature as optional to the market place entry.

Seems to work without it. But I added it anyway.

**Pull request merged**
