### PR TITLE
Fix links to Dart & Flutter

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
@vogella this replaces https://github.com/eclipse/dartboard/pull/65. I fixed the missing email in the commit. Why is the CLA bot still complaining? What does `did not include the "Signed-off-by footer" which is required for all commits made by a contributor.` mean?

**Comment by jonas-jonas** [comment]
Hi @mit-mit,

thanks for updating the PR. 
Every commit to an EPL licensed project needs to contain a `Signed-off-by footer` which looks like this: `Signed-off-by: Jonas Hungershausen <jonas.hungershausen@vogella.com>` (in this case for me). You would replace the name and email parts with your details, you signed the ECA with. 
Footer here means the 3rd line in the commit message.
See https://github.com/eclipse/dartboard/commit/2bf44b2a941504c451ee3962ce56feaf2b0d8c57 for an example. 

In this case you could just amend the commit with the footer and force-push to the same branch so you don't have to open another PR.

**Comment by mit-mit** [comment]
Sorry, this is getting a bit too complicated for a one liner change. I logged an issue; maybe you can fix it? https://github.com/eclipse/dartboard/issues/72

**Comment by vogella** [comment]
@mit-mit sorry for this overhead. The Eclipse process is more designed for code contributions. Thanks for helping with docu updates.

**Pull request closed without merging**
