### PR TITLE
Add icon to run Dart project #52

### PR DESCRIPTION
**Pull request by lak-proddev**
Signed-off-by: Lakshminarayana Nekkanti <narayana.nekkanti@gmail.com>

Added temporary 16x16 icon for time being. 
SS after adding image

image

image

### CODE REVIEW

**Comment by jonas-jonas** [comment]
Hi Lakshminarayana,

thank you very much for your PR. Unfortunately we can't merge this PR right now, because we are currently awaiting approval by Google and the Eclipse Foundation to use the icon. See http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20229 for more information.

Concerning the original PR, I would like it if the icon would have a transparent background. Currently it seems like the background of the .png is white, which is not ideal. Could you amend the PR to include a png file with a transparent background?

**Comment by lak-proddev** [comment]
> Hi Lakshminarayana,
> 
> thank you very much for your PR. Unfortunately we can't merge this PR right now, because we are currently awaiting approval by Google and the Eclipse Foundation to use the icon. See http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20229 for more information.
> 
No problem, I also would like to part of this project when time permits. I don't have ipzilla access  :)

> Concerning the original PR, I would like it if the icon would have a transparent background. Currently it seems like the background of the .png is white, which is not ideal. Could you amend the PR to include a png file with a transparent background?
 
I agree. I just used a temporary  image to show. I try to push a transparent background.

**Comment by jonas-jonas** [comment]
Thanks for updating the icon.

As I said, I will merge the PR once we have full permission to use the Logo inside the project. Thanks for your patience.

**Comment by vogella** [comment]
Can we uses placeholder icon in the meantime?

Jonas Hungershausen <notifications@github.com> schrieb am So., 30. Juni
2019, 14:00:

**Comment by jonas-jonas** [comment]
> Can we uses placeholder icon in the meantime? 

I wouldn't know what icon we could use. Currently there is just a red dot. Any suggestions welcome.

Also, we should get permission relatively soon. So it shouldn't take that long anyway.

**Comment by vogella** [comment]
The material design icons are ok to use, I requested them a while ago.

Otherwise pick any from eclipse.platform.images repo

Jonas Hungershausen <notifications@github.com> schrieb am So., 30. Juni
2019, 14:49:

**Comment by lak-proddev** [comment]
>>" The author(s) of the pull request is not covered by necessary legal agreements in order to proceed."

How to solve this?

**Comment by jonas-jonas** [comment]
> How to solve this?

You need to sign off the merge commit as well. Amend the sign-off and force push should fix it.

**Pull request merged**
